# Generated by Django 2.2.16 on 2022-12-24 16:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221222_0250'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_cannot_rate_themselves',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='users_cannot_follow_themselves'),
        ),
    ]
