# Generated by Django 2.2.16 on 2022-12-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20221224_2128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_cannot_follow_themselves',
        ),
    ]
